### ISSUE TITLE
too many "Server throttling - sleeping for a bit" Warnings

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/pokeminer#15]
I have them like 1-3 times / minute with 25 Workers think that isn't good

**Comment by Noctem** [comment]
Do you have encounter/spinning/bag-cleaning enabled?

I'm not getting these currently, but it's quite possible that the delay times for some of those features need to be tweaked.

**Comment by evenly-epic-mule** [comment]
yep I had (spinning/bag-cleaning), but I checked the times and they are fine, I can do the stuff in the same time +/- 0.3 seconds, except for cleaning with +50 items, but adding a `+count*0.05` to the action hasn't fixed it

**Comment by Noctem** [comment]
Did 3bb0e1c fix this for you?

**Comment by evenly-epic-mule** [comment]
I currenlty kind of lack the time to rebase my branch and merge it - I may check it this weekend

**Comment by evenly-epic-mule** [comment]
the Warnings have gone down to about 10-20 / day with 150 Workers & 5k spawns, so I'd say this should be fine
