### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xDyN** [Noctem/pokeminer#2]
F:\pokeminer>python -i
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\pokeminer\db.py", line 12, in <module>
    import utils
  File "F:\pokeminer\utils.py", line 4, in <module>
    import polyline
ImportError: No module named 'polyline'
>>> db.Base.metadata.create_all(db.get_engine())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'db' is not defined
>>> db.Base.metadata.create_all(db.get_engine())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'db' is not defined
>>>
what happen with me ?

**Comment by xDyN** [comment]
and
Running setup.py install for xxhash: finished with status 'error'
    Complete output from command c:\python35\python.exe -u -c "import setuptools                                                                                                                , tokenize;__file__='C:\\Users\\Windows 7 Blue\\AppData\\Local\\Temp\\pip-build-                                                                                                                7ib2tz0q\\xxhash\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.r                                                                                                                ead().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" ins                                                                                                                tall --record "C:\Users\Windows 7 Blue\AppData\Local\Temp\pip-6hsvn30q-record\in                                                                                                                stall-record.txt" --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'xxhash' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual                                                                                                                 C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\                                                                                                                \Users\\Windows 7 Blue\\AppData\\Local\\Temp\\pip-build-7ib2tz0q\\xxhash\\setup.                                                                                                                py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\                                                                                                                n');f.close();exec(compile(code, __file__, 'exec'))" install --record "C:\Users\                                                                                                                Windows 7 Blue\AppData\Local\Temp\pip-6hsvn30q-record\install-record.txt" --sing                                                                                                                le-version-externally-managed --compile" failed with error code 1 in C:\Users\Wi                                                                                                                ndows 7 Blue\AppData\Local\Temp\pip-build-7ib2tz0q\xxhash\

**Comment by Noctem** [comment]
The first error is because `polyline` isn't installed. Make sure you have all of the requirements.
```bash
pip3 install -U requirements.txt
```
The second one is about failing to build `xxhash`, which is no longer required for pgoapi so I removed it from my pgoapi's *requirements.txt* just now. That shouldn't be a problem any more.

**Comment by xDyN** [comment]
today I try setup and get new error
>>> import db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\pokeminer\db.py", line 12, in <module>
    import utils
  File "G:\pokeminer\utils.py", line 9, in <module>
    from pgoapi import utilities as pgoapi_utils
  File "g:\pokeminer\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "g:\pokeminer\src\pgoapi\pgoapi\pgoapi.py", line 35, in <module>
    from pgoapi.rpc_api import RpcApi
  File "g:\pokeminer\src\pgoapi\pgoapi\rpc_api.py", line 48, in <module>
    from pogoprotos.networking.envelopes.request_envelope_pb2 import RequestEnvelope
ImportError: No module named 'pogoprotos'

**Comment by Noctem** [comment]
Oops. There were some issues with case sensitivity on my pgoapi repo. It should work now.

**Comment by xDyN** [comment]
>>> import db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\pokeminer\db.py", line 12, in <module>
    import utils
  File "G:\pokeminer\utils.py", line 11, in <module>
    import config
  File "G:\pokeminer\config.py", line 3, in <module>
    from landmarks import Landmarks
  File "G:\pokeminer\landmarks.py", line 1, in <module>
    from shapely.geometry import Point, Polygon, shape, box, LineString
ImportError: No module named 'shapely'

I can't install shapely ! do you know how to fix that ?

**Comment by Noctem** [comment]
Are you using notifications/landmarks or `BOUNDARIES`? If not, you can just remove:
```python
from landmarks import Landmarks
```
from your *config.py*, and shapely will no longer be needed.

If you are using it, `pip3 install shapely` should work. It's in *optional-requirements.txt* if you were wondering why it didn't get included when you installed everything in *requirements.txt*.

**Comment by xDyN** [comment]
when I remove 
`from landmarks import Landmarks`
I get error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\pokeminer\db.py", line 12, in <module>
    import utils
  File "G:\pokeminer\utils.py", line 11, in <module>
    import config
  File "G:\pokeminer\config.py", line 91, in <module>
    LANDMARKS = Landmarks(query_suffix=AREA_NAME)
NameError: name 'Landmarks' is not defined

I remove all line have Landmarks , it work but when I run worker.py I get error

 python worker.py -st 8
Traceback (most recent call last):
  File "worker.py", line 1349, in <module>
    with open('pickles/accounts.pickle', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pickles/accounts.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "worker.py", line 1358, in <module>
    ACCOUNTS = utils.create_accounts_dict()
  File "G:\pokeminer\utils.py", line 325, in create_accounts_dict
    accounts[username] = create_account_dict(account)
  File "G:\pokeminer\utils.py", line 311, in create_account_dict
    entry.update(utils.generate_device_info())
NameError: name 'utils' is not defined

**Comment by Noctem** [comment]
Ahh, that's a bug. I've pushed a fix, although it doesn't seem to be showing up on GitHub yet due to the [service outage](https://status.github.com/). Thanks for bringing that to my attention, I'm not sure how I missed it.

This is the fix:
```diff
diff --git a/utils.py b/utils.py
index 4b73206..12e37cb 100644
--- a/utils.py
+++ b/utils.py
@@ -308,7 +308,7 @@ def create_account_dict(account):
     if length == 4 or length == 6:
         entry['model'], entry['iOS'], entry['id'] = account[-3:]
     else:
-        entry.update(utils.generate_device_info())
+        entry.update(generate_device_info())

     entry.update({'location': (0,0,0), 'time': 0, 'captcha': False, 'banned': False})
```

Also, FYI: *worker.py* relies on having a database table of spawnpoints and their expiration times. I recently added *wander.py* which uses the old method of scanning every 70m. I haven't tested that much yet, so let me know if you use it and encounter issues. Most of my development effort will go towards spawnpoint scanning, but I'd like to have something to let people that are starting fresh build up a spawn DB. The spawnpoint database will automatically expand as they discover Pokemon with accurate expiration timestamps, so you can switch over to *worker* as soon as you have enough points to keep your workers busy.

**Comment by xDyN** [comment]
hmm i get a new error

`$ python worker.py
Traceback (most recent call last):
  File "worker.py", line 1376, in <module>
    import notification
  File "G:\Pokeminer\notification.py", line 6, in <module>
    import cairo
ImportError: No module named 'cairo'
`

**Comment by Noctem** [comment]
You're not using notifications, right? It's importing *notification* which was importing *cairo* because you apparently have either `NOTIFY_IDS` or `NOTIFY_RANKING` in your config which it was using to determine that you want to use notifications.

Some additional checks that I added in 0c6135178b28f67974a3b3b140a7a613fcbb4f18 will likely resolve that particular issue for you, but it would still be wise to remove any configuration options that are only relevant to notifications if you're not using that feature. That commit also comments out those options from the config.example.

**Comment by xDyN** [comment]
`$ python worker.py
Traceback (most recent call last):
  File "worker.py", line 1402, in <module>
    overseer.start()
  File "worker.py", line 954, in start
    self.launch_account_manager()
  File "worker.py", line 913, in launch_account_manager
    self.manager.start(mgr_init)
  File "F:\Python35\lib\multiprocessing\managers.py", line 479, in start
    self._process.start()
  File "F:\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "F:\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "F:\Python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __ini                                                                                                                t__
    reduction.dump(process_obj, to_child)
  File "F:\Python35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Overseer.launch_account_manager.<loca                                                                                                                ls>.<lambda>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\Python35\lib\multiprocessing\spawn.py", line 100, in spawn_main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "F:\Python35\lib\multiprocessing\reduction.py", line 86, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied

`
i get a error

**Comment by Noctem** [comment]
Does 4d12aab380fa04d947f8f3a10912a555bc7dafb2 fix that?

**Comment by Noctem** [comment]
e102bd74d91170a6e54d2160f504177c6a9e3b25 should fix that.

**Comment by xDyN** [comment]
I will setup this ! hope it don't have error !
