### ISSUE TITLE
Invalid authentication provider - only ptc/google available.

### ISSUE THREAD

**Issue by brazgardian** [Noctem/pokeminer#315]
I cannot get the manual captcha solving to work. 
I have about 40 accounts and am using a grid of 4x4.  
All the accounts were made on the PTC website, and are not linked with google at all. 
I get a few captcha pretty quickly while running scan.py then I run solve_captchas.py in a new command window and am met with the below error after chrome opens with a blank page at the "data" url. 

aiopogo error on <account name>: Invalid authentication provider - only ptc/google available

Any ideas how to solve this?  I have only filled in the username/password in the accounts.csv file (as the readme states). When I add the provider as "ptc", it makes no difference. 

Further, I have verified that the provider being passed to aiopogo is just an empty string.

If I then force the provider (hardcode it) at Line 83 of solve_captchas.py to be 'ptc', then I get a hash server unavailable error... I definitely do not want to be using a hash server since I have no paid for any.  

EDIT: I am on Win 7 using python 3.6.1

**Comment by brazgardian** [comment]
While it is still a bit confusing to use. I was able to get it working by deleting the monocle cache and pickles. It still gives me a continuous error (shown below), but I guess it eventually solves it.. so I am closing this issue.  As another note, my internet connection can be very slow so I am not sure if that has something to do with this issue.

"aiopogo error on XXXX: Hashing server error 503: Service Unavailable"

**Comment by M3G4THEKING** [comment]
@garrickbrazil Hashing server error= problems with bossland not with monocle
