### ISSUE TITLE
[Feature Request] Treat raid battle time as a TTL spawn point to be visited

### ISSUE THREAD

**Issue by baskettcase** [Noctem/pokeminer#318]
As the title says, it would be nice to treat raid battle start time as a spawn point with a TTL, so that a worker can be queued to go visit the gym to get the new raid info.

**Comment by baskettcase** [comment]
Im thinking this might not be necessary since gyms are pulled in on pretty much every request and there is such a large range where gyms are found that at all times there is probably at least one worker within a gym area.. so maybe pointless?

**Comment by DavePlater** [comment]
When legendarys came out, eggs for raid bosses went away, so it wouldn't be helpful anymore. Unless theyre going to go back to that?

**Comment by baskettcase** [comment]
Yeah I agree.. this does seem pointless now for a lot of different reasons. Ill just close it out.
