### ISSUE TITLE
Questions / Issues

### ISSUE THREAD

**Issue by MrCanan** [Noctem/pokeminer#326]
Hi,

First, thanks for your awesome work.

I don't find any Discord to post, so I post here for the moment. =)

I have some questions / problems about Monocle installtion and usage : 
1. I set a valid BOUNDARIES, but I still see the rectangle
2. I can start without errors the three first scripts : "create_db.py", "scan.py" and "web.py". But I can not start "gyms.py" after, because he gives me an ERRNO error : "OSError: [Errno 98] Address already in use"

I hope someone will be able to help me, because I miss probably something.

Very cordially.

**Comment by walaoaaa1234** [comment]
@MrCanan inviting you to Monocle discord.

**Comment by mathaupt** [comment]
would be nice if you would send me the link too, currently, running 2 instances, different code base until there is a merge for the raid pr

**Comment by walaoaaa1234** [comment]
@mathaupt [Discord](https://discordapp.com/invite/Hb2umg)
EDITED

**Comment by mathaupt** [comment]
invalid :/

**Comment by walaoaaa1234** [comment]
@mathaupt link updated

**Comment by MrCanan** [comment]
Thanks a lot to every members who send me a private invitation and help me on your Discord.
You are so much more friendly, fast and understandable than your competitors. =)

**Comment by DavePlater** [comment]
I'd like to get in on the discord server too?
I've had various little quirk questions that i dont want to clutter the posts with.

As for your 2nd question, gyms.py is i feel, a dead script. It launched a web instance that gave some outdated statistics about the gyms in the area. (it conflicts with web.py)

**Comment by vafrederico** [comment]
@walaoaaa1234 Can you invite me as well? i've been looking for this for a  while

**Comment by CTMapper** [comment]
Also looking for the Monocle discord.  Can you invite?  Thx!

**Comment by M3G4THEKING** [comment]
https://discord.gg/ZXb6ZW5 @CTMapper
