### ISSUE TITLE
Not enough accounts

### ISSUE THREAD

**Issue by Cepumins** [Noctem/pokeminer#337]
Hello there,

So today i was setting up Monocle scanner, (im new to python) but i ran into error. It says "You don't have enough accounts for the number of workers specified in GRID." I have tried adding even more accounts or reducing grid to 1*1, but nothing works. I have no clue what can i modify to make it work.

![cmd](https://user-images.githubusercontent.com/30569014/28752829-39cc2df6-7531-11e7-8b36-deb886b78ab8.png) - cmd error

![config](https://user-images.githubusercontent.com/30569014/28752831-4b337d24-7531-11e7-9439-369f00b811a5.png) - config

![accounts](https://user-images.githubusercontent.com/30569014/28752835-522d92d6-7531-11e7-973a-d15d92b93393.png) - more than enough accounts

Thanks in advance for help. Just let me know and I will more than happily provide more specific detail of my setup.

Cepumins

**Comment by DavePlater** [comment]
You need to re-run create_db.py after making any of those changes.

**Comment by Cepumins** [comment]
I tried it and it spat out the same error. Should i delete anything that running "python3 scripts/create_db.py" command creates?
Cepumins

**Comment by Cepumins** [comment]
I created a new file and copied config & accounts then did tutorial and it seems to run now! Thanks a bunch!
Cepumins
