### ISSUE TITLE
No sightings

### ISSUE THREAD

**Issue by Cepumins** [Noctem/pokeminer#340]
Hello there,
As of now i have been running monocle for 2h and none of the bots can find any sightings.
Thanks in advance for help.
Cepumins

**Comment by DavePlater** [comment]
What does your scan.log file say?
In the scan.py output, did all of your accounts make it though the login process?

**Comment by Cepumins** [comment]
Yes, reading it i get that all accounts made trough login proccess.
[scan.txt](https://github.com/Noctem/Monocle/files/1194917/scan.txt)
Heres the log file

Cepumins

**Comment by DavePlater** [comment]
I would say stop your instance. Clear out all the scan.log files and start again. 
That log file was just flooded with errors. All of them say your workers never even made it to being logged in.

Do you have a correct HASH_KEY specified? (you have to buy one)

**Comment by Cepumins** [comment]
Thank you very much it fixed the error! I had # before HASH_KEY.
Cepumins
