### ISSUE TITLE
No pokemon found during the scan

### ISSUE THREAD

**Issue by MasterCynder** [Noctem/pokeminer#363]
No pokemons are found during the scan.
Hash key is correct, accounts seems to be correct, location is correct
![image](https://user-images.githubusercontent.com/11613308/30137741-0c926790-9365-11e7-859e-f1a87b422580.png)

Any idea about this issue ?

**Comment by JasonKhew96** [comment]
@MasterCynder it is looking for spawnpoints and timer, wait for a few hours

**Comment by MasterCynder** [comment]
The problem is solved.
The ubuntu firewall ufw was active by default (sudo ufw status to know if it's enable or not)

To disable : sudo ufw disable

Thank's
