### ISSUE TITLE
Workers outside location

### ISSUE THREAD

**Issue by m3g4mInD** [Noctem/pokeminer#38]
I dont know if is a bug or something in my cfg,but i have several works like 20% outside of my location  http://prntscr.com/dwunha

My cfg:

[http://pastebin.com/raw/AfqbqhtT](url)

**Comment by Noctem** [comment]
Probably an issue with mysteries in the pickle. Running `scan.py --no-pickle` should fix it.

I'll probably prevent this from happening soon.

**Comment by m3g4mInD** [comment]
I'am testing now,after 1h i let my feedback and thanks for help us :)
