### ISSUE TITLE
import db problem, any ideas?

### ISSUE THREAD

**Issue by baskettcase** [Noctem/pokeminer#40]
Since Im not a Python user, any ideas on why Im getting this error when trying to "import db" according to your directions? This is in OS X.

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/db.py", line 14, in <module>
>     import utils
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/utils.py", line 13, in <module>
>     from pgoapi import utilities as pgoapi_utils
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/pgoapi/__init__.py", line 50, in <module>
>     from pgoapi.pgoapi import PGoApi
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/pgoapi/pgoapi.py", line 37, in <module>
>     from pgoapi.auth_google import AuthGoogle
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/pgoapi/auth_google.py", line 32, in <module>
>     from gpsoauth import perform_master_login, perform_oauth
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/gpsoauth/__init__.py", line 4, in <module>
>     from . import google
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/gpsoauth/google.py", line 4, in <module>
>     from Cryptodome.PublicKey import RSA
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/Cryptodome/PublicKey/RSA.py", line 79, in <module>
>     from Cryptodome.IO import PKCS8, PEM
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/Cryptodome/IO/PKCS8.py", line 73, in <module>
>     from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/Cryptodome/IO/_PBES.py", line 44, in <module>
>     from Cryptodome.Cipher import DES, ARC2, DES3, AES
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/Cryptodome/Cipher/__init__.py", line 78, in <module>
>     from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/Cryptodome/Cipher/_mode_ecb.py", line 46, in <module>
>     """
>   File "/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.5/site-packages/Cryptodome/Util/_raw_api.py", line 168, in load_pycryptodome_raw_lib
>     raise OSError("Cannot load native module '%s'" % name)
> OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

**Comment by Noctem** [comment]
Something's going wrong with the encrypt lib. How did you install Python 3? Installing from [homebrew](http://brew.sh/) would probably fix the problem.

```bash
brew install python3
```

**Comment by baskettcase** [comment]
Ok I did it that way instead and now Im getting a different error. 

> ModuleNotFoundError: No module named 'MySQLdb'

so then I did this after a bit of research

`pip3 install mysqlclient`

and now when I try to import db I get this:

> ImportError: dlopen(/Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.6/site-packages/_mysql.cpython-36m-darwin.so, 2): Library not loaded: libmysqlclient.18.dylib
>   Referenced from: /Users/pokemongo/Sites/git-repositories/pokeminer/venv/lib/python3.6/site-packages/_mysql.cpython-36m-darwin.so
>   Reason: image not found

**Comment by Noctem** [comment]
Try installing `MySQL-python` instead.

**Comment by baskettcase** [comment]
I tried that first and got this error `ModuleNotFoundError: No module named 'ConfigParser'` and it sounded like that one doesn't support python3 like you said.

**Comment by baskettcase** [comment]
Ok I got this one figured out.. or you guys did :) I updated to the latest and everything worked fine this time. I have another problem now so Ill make another post.
