### ISSUE TITLE
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].

### ISSUE THREAD

**Issue by baskettcase** [Noctem/pokeminer#46]
I decided to install this on my linux server instead of my computer (OS X) but now Im getting another error which I try to "import db"

lots of traceback and then the subject error

OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].

I installed geos, but that didn't work

**Comment by m3g4mInD** [comment]
@baskettcase  try   sudo apt-get install libgeos-dev

**Comment by baskettcase** [comment]
Is there a way to do this on a shared environment with pip in a venv?

**Comment by baskettcase** [comment]
Im having this problem in OS X also, so OS X and CentOS 6

**Comment by baskettcase** [comment]
I installed as root on the server with yum, so that seems to have fixed things. Thanks!
