### ISSUE TITLE
BUG: SPAWN_ID_INT = False has issues with db insertion

### ISSUE THREAD

**Issue by baskettcase** [Noctem/pokeminer#54]
I am using MySQL for the database and I have 

SPAWN_ID_INT = False

and I am seeing a lot of problems in my scan.log like these:

SELECT max(seen_range)\n        FROM mystery_sightings\n        WHERE spawn_id = [REMOVED, but it's alphaneumeric]\n        AND first_seen > 1484092800

Which because there are no quotes around the spawn_id it is failing.. since it's not a number...

**Comment by baskettcase** [comment]
This happens in pokeminer/pokeminer/db.py get_first_last() and get_widest_range() methods

**Comment by Noctem** [comment]
af2ed4f should fix this.
