### ISSUE TITLE
Could not spin xxxxxx because inventory was full. 346

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/pokeminer#7]
seams like it failes to read the items correctly(?)

**Comment by evenly-epic-mule** [comment]
https://github.com/Noctem/pokeminer/pull/8 should fix it

**Comment by Noctem** [comment]
Do you still get this on the latest `develop` commit? 

I stopped getting it when I changed:
```python
sum(self.items.values()) > self.item_capacity
```
to:
```python
sum(self.items.values()) >= self.item_capacity
```
in bfad7ba.

**Comment by Noctem** [comment]
If there is a bug with the inventory then I'd like to fix that instead of working around it with more bag cleaning. Is there any reason any of your account inventories would change between scans? Even then it should get updated during the initial login, unless the pickled auth info is still valid.

**Comment by evenly-epic-mule** [comment]
could be related to https://github.com/Noctem/pokeminer/issues/11

**Comment by evenly-epic-mule** [comment]
I haven't had this lately, but the `346` is the sum of the items.

A different cause except for #11 could be that maybe at some point `update_inventory` went wrong and since we only select the changes since `self.inventory_timestamp` the items were out of sync

I'll close it as I haven't had the message for ages
